### ISSUE TITLE
Add ability to create custom wavelength params

### ISSUE THREAD

**Issue by melix** [melix/astro4j#15]
Currently the known spectral rays are hardcoded as an enum: https://github.com/melix/astro4j/blob/56c1dacb325124533bd66f6334dd3b3bb7872622/jsolex-core/src/main/java/me/champeau/a4j/jsolex/processing/params/SpectralRay.java#L29-L34

A user has expressed interest in adding their own wavelengths. We should evaluate how to do this, in particular in such a way it is compatible with the CLI version.

**Comment by stephaneferier** [comment]
Thanks Cédric!
