### ISSUE TITLE
Request to allow sun detection threshold to be a settable parameter in jSolEx

### ISSUE THREAD

**Issue by stefanoaz** [melix/astro4j#263]
Hello Cedric:

I'm finding that I'm having some issues with jSolEx detecting the spectral line in my ROI. When I use the Spectrum Debugger, I find that by adjusting the Sun Detection Threshold parameter, I can get detection almost all the time. (D. Smith's SHG seems to detect polys better than INTI or JSolEx, but without the great features you've added otherwise).

I wonder if a Dev version jSolEx could be made allowing the Sun Detection Threshold to be settable, with the standard auto setting as default, for troublesome SER files. I may have low luminosity in some of my SER files, but I also get issues if I set the exposure high.

**Comment by melix** [comment]
Sure I can make that happen. I wanted to avoid it (too many parameters tend to become complicated for users) but I can certainly add something. Out of curiosity, does it happen with latest 2.3.x releases too? I'm improving the detection algorithm in different versions, so you may see differences.

**Comment by stefanoaz** [comment]
Hi Cedric:

Yes - I'm using the latest V2.3.1. And I have found differences - occasionally 2.2.4 gets a detect that 2.3.12 willl not, but not often. I'm finding that jSolEx is not detecting many files that DSmith's SHG does detect - and I thing it may be related to lower luminance in some of my files. This would be a terrific way to debug things, if I could have a handle on the detection parameter. The UI could set it to default for mmost users. I'll be happy to report back what I find.

Thanks,

Steve Rector

**Comment by melix** [comment]
If you have the opportunity, I'd be glad to get one (or more) SER files which don't work with JSol'Ex.

**Comment by stefanoaz** [comment]
Hi Cedric:

I have ser files that I can send, but they're around 3.6GB each and would exceed my dropbox capacity. Any way I can get one to you by another means?

Steve

**Comment by melix** [comment]
Sure you can use a service like WeTransfer.

**Comment by melix** [comment]
I got the file, thank you, I'll keep you posted!

**Comment by stefanoaz** [comment]
Thanks Cédric - I'll clear it out then thanks. BTW, I saw your Devoxx presentation on Youtube - first rate and good info. I'll try out the Dev 2.3.2 today.

Steve
