### ISSUE TITLE
Doppler feature needs option for B-R reversal

### ISSUE THREAD

**Issue by stefanoaz** [melix/astro4j#285]
Hi Cédric. I have found that, depending on the direction of scan, the image reconstruction requires vertical and horizontal flip options to get a successful alignment to a GONG reference image. You have these. However, I have found with Inti, that I need the option that Valerie has for B-R reversal. This is because, depending on the reflections I have used to get the proper orientation, the Blue and Red sides of the Doppler from solar rotation can be reversed. That is happening with your new (and very welcome) addition of the doppler image. 

There needs to be a selection for B-R reversal to correct this issue.

Steve

**Comment by melix** [comment]
The option already exists, here (it was there before INTI had it ;)) :

![image](https://github.com/melix/astro4j/assets/316357/997689b5-9768-4032-9c76-5229ae049db2)

**Comment by stefanoaz** [comment]
Oh - okay, that's great :)  I didn't realize that was for the doppler function - I thought maybe jSolEx had the ability to process RGB images (I have never tried it). It was not clear to me that was for the doppler, since that's a relatively new feature.

Thanks for clarifying.
