### ISSUE TITLE
Cameras with small pixels need a larger offset for continuum image

### ISSUE THREAD

**Issue by stefanoaz** [melix/astro4j#286]
Hi Cédric:

I'm using jSolEx V2.4.0 with a new camera: QHY-678, which has 2µm pixel size (although this is oversampled on a 72mm aperture scope). With small pixels, the 15 pixel offset is too low to exit far enough out of the H-alpha wing - there are still significant vestiges of H-alpha features at this offset. I find that, with a 2µm pixel I need 26-30 pixels offset to get a good continuum in Inti. 

It would be good if the user could enter a number in a field to specify the continuum offset. There could be a suggested default for new users, perhaps.

Steve

**Comment by stefanoaz** [comment]
I just saw that I can specify the offset in the custom processing option. It still might be good to allow the user to specify the offset that corresponds to "continuum" in the full processing option.

**Comment by stefanoaz** [comment]
Related to the custom processing workaround for specifying offset: I just noticed that when I custom process a new SER file, the offset field does not retain the prior value I entered for offset - it resets that value to 15 pixels.

**Comment by melix** [comment]
Fixed in #289
