### ISSUE TITLE
Helium D3 auto-misdetection

### ISSUE THREAD

**Issue by vnp85** [melix/astro4j#314]
First of all, **thank you** for your software.

**Bug description**
I open a ser recording of a spectroheliogram around the helium D3 line. Quick mode misidentifies the spectral line, and the resulting Helium D3 extraction is just noise. 

**Perhaps make this into a feature request**
Make the number, next to the Helium D3 editable.

**Reproduction**
Ver. 2.5.0
Use a recording that has no Sodium D lines in it, and the iron etc. in the vicinity are slightly obscure. Run quick mode. If the Helium D3 option shows up, chances are, it misses the line. In the uploaded image it is at -66 pixels from the detected spectral line, while JSol'Ex proposes -142.

Expected: the Helium D3 number to be around -66 in this case
Observed: the Helium D3 extraction, if available at all, is -142 or so

I uploaded the average png, the helium line is around the middle of the image, two absorption lines below, one above it.

![image](https://github.com/melix/astro4j/assets/21062213/3159ff51-6ec9-47a5-90d9-a060a5c121d8)

**Comment by melix** [comment]
The most likely explanation is that you have incorrectly set the "pixel size" in observation details. Can you double check?

**Comment by vnp85** [comment]
This is my log, the pixel size looks correct.

`13:41:41.234 [INFO] Output directory set to D:\2024-06-24\Sun-He-rp
13:41:41.236 [INFO] File 2024-06-24-0749_3-Sun-He-rp.ser
13:41:41.236 [INFO] Found Sharpcap metadata. Camera ZWO ASI678MM Binning 1
13:42:21.765 [INFO] Dimensions of raw image determined : 3696x5309
13:42:21.808 [INFO] Processing will require approximatively 673.67MB of disk space
13:42:21.978 [INFO] Detected spectral line Iron (Fe I) with binning 1 (for pixel size 2.00µm)
13:42:21.984 [INFO] Starting reconstruction...
13:42:21.984 [INFO] Distortion polynomial ax3 + bx2 + cx + d = 0
   - a = -7.323243917886016E-11
   - b = 1.3521994335958624E-5
   - c = -0.045643179541491635
   - d = 247.08835704559624
13:42:57.450 [INFO] Reconstruction done. Generating images...
13:43:36.549 [INFO] Black estimate 275.94
13:43:41.960 [INFO] Detected X/Y ratio: 1.16
13:44:10.706 [INFO] Processing done
13:44:10.711 [INFO] Finished in 149.45s
`

**Comment by vnp85** [comment]
PS: it did work well with this average, containing a prominent sodium line
![image](https://github.com/melix/astro4j/assets/21062213/79d395e0-7e84-460b-b608-834e4e70a40a)

**Comment by melix** [comment]
Would it be possible for you to share the SER file?

**Comment by vnp85** [comment]
Yes, give me a sec.

**Comment by melix** [comment]
If the pb is that JSol'Ex confuses the Fe I line with Sodium D2, you should be able to select one or the other explicitly.

**Comment by vnp85** [comment]
Letting the user edit the proposed number and method of extraction, could make it possible to inspect other lines as well. 

Helium D3 (method: subtraction) [pixel distance]
Some line (method: as is) [pixel distance]

Some line: like hydrogen epsilon, near CaH 

So this is the ser with the mis-detection. One can actually see, in the flash spectrum, the magnificent proms visible today, so there's the Helium line, no doubt. (The hosting server is a raspberry, a bit slow on the bandwidth) 

(~10 GB) http://narnia.go.ro/seagate2tb/2024-06-24/2024-06-24-0749_3-Sun-He-rp.ser

**Comment by vnp85** [comment]
Here's the prom, frame extracted via AS4 and gamma applied

![image](https://github.com/melix/astro4j/assets/21062213/64cdc90c-1332-433e-9c2c-11b631a11bdf)

**Comment by melix** [comment]
Thanks, I'll take a look. 10GB SER file wow :) Regarding editing pixel distance, in this case it is easier to use scripts. It doesn't really make sense to add a parameter here since it is designed to work automatically. If it fails, then it's a bug that I should fix (or misconfiguration). You actually have one sample script which does Helium line extraction that you can tweak when you open the ImageMath mode (see also https://melix.github.io/astro4j/latest/en/jsolex.html#imagemath).

**Comment by vnp85** [comment]
Thank you, I will take a look at the ImageMath helium alternative.
The hydrogen epsilon isn't a big deal, I can just manually type a pixel shift value.

Off topic: do you know of a script that, given an image input (a snapshot from Sharpcap) can come back with wavelengths and lines seen (don't want to reinvent warm water)? Ideally with no parameters but reference data like snapshots around known spectral lines, like the Fraunhofers, either the Sodium or the Magnesium should be good starting points...

**Comment by melix** [comment]
> Off topic: do you know of a script that, given an image input (a snapshot from Sharpcap) can come back with wavelengths and lines seen (don't want to reinvent warm water)? Ideally with no parameters but reference data like snapshots around known spectral lines, like the Fraunhofers, either the Sodium or the Magnesium should be good starting points...

Yes, you can use INTI Map for this. It's still experimental AFAIK and I've got varying results on it.

**Comment by vnp85** [comment]
Regarding the spectral line -- see the Helium question -- I identified it
as the He I at 447.15 nm, exactly as planned my session, but wasn't sure
about the line. However, the result is ugly.

Cédric Champeau ***@***.***> ezt írta (időpont: 2024. jún.
24., H, 14:59):

**Comment by melix** [comment]
Ah right, but JSol'Ex automatic processing is only available for the D3 line. You can do exactly what you want with the scripts though. In particular look at the `find_shift` function.

**Comment by vnp85** [comment]
I'll look into it. 

I hope you find the bug around the D3 line (I think it's going to be a pattern thing, though my Java knowledge is more than rusty). Visually, having seen this on my screen before switching to slit view, was mesmerizing.

![image](https://github.com/melix/astro4j/assets/21062213/b71915f4-e93d-4a2b-ba0e-3494f9b983ad)

**Comment by melix** [comment]
Is this done with a Sol'Ex or another SHG? Seems that the resolution if fairly high. From what I can tell, your crop window does _not_ contain the Fe I line, which explains that JSol'Ex mismatched. 

![image](https://github.com/melix/astro4j/assets/316357/ad8b70f6-366f-432f-85bc-b2e0473d28aa)

**Comment by vnp85** [comment]
Very same Sol'Ex and 678MM with 2um pixels, different crop. I double checked.

I have a vertically full size still, a larger video that does contain a Sodium D line, and then several that don't contain the Sodium D line.

The one on the left, with the Sodium line works, and extracts Helium, the one on the right doesn't, albeit it is a crop of it.

![image](https://github.com/melix/astro4j/assets/21062213/18143814-e572-41fc-b887-5ecca124d4a6)

The left one's logs

`12:29:20.685 [INFO] Output directory set to D:\2024-06-24\Sun-He
12:29:20.686 [INFO] File 2024-06-24-0741_6-Sun-He.ser
12:29:20.686 [INFO] Found Sharpcap metadata. Camera ZWO ASI678MM Binning 1
12:30:01.463 [INFO] Dimensions of raw image determined : 3696x2925
12:30:01.476 [INFO] Processing will require approximatively 371.16MB of disk space
12:30:01.816 [INFO] Detected spectral line Sodium (D2) with binning 1 (for pixel size 2.00µm)
12:30:01.845 [INFO] Starting reconstruction...
12:30:01.845 [INFO] Distortion polynomial ax3 + bx2 + cx + d = 0
   - a = 1.9976882786697787E-11
   - b = 1.2857778816395939E-5
   - c = -0.04431522371117369
   - d = 490.60568624414543
12:30:43.442 [INFO] Reconstruction done. Generating images...
12:30:49.851 [INFO] Black estimate 242.21
12:30:59.247 [INFO] Detected X/Y ratio: 0.74
12:31:19.942 [INFO] Processing done
12:31:19.944 [INFO] Finished in 119.25s
`

The right one's

`
13:41:41.234 [INFO] Output directory set to D:\2024-06-24\Sun-He-rp
13:41:41.236 [INFO] File 2024-06-24-0749_3-Sun-He-rp.ser
13:41:41.236 [INFO] Found Sharpcap metadata. Camera ZWO ASI678MM Binning 1
13:42:21.765 [INFO] Dimensions of raw image determined : 3696x5309
13:42:21.808 [INFO] Processing will require approximatively 673.67MB of disk space
13:42:21.978 [INFO] Detected spectral line Iron (Fe I) with binning 1 (for pixel size 2.00µm)
13:42:21.984 [INFO] Starting reconstruction...
13:42:21.984 [INFO] Distortion polynomial ax3 + bx2 + cx + d = 0
   - a = -7.323243917886016E-11
   - b = 1.3521994335958624E-5
   - c = -0.045643179541491635
   - d = 247.08835704559624
13:42:57.450 [INFO] Reconstruction done. Generating images...
13:43:36.549 [INFO] Black estimate 275.94
13:43:41.960 [INFO] Detected X/Y ratio: 1.16
13:44:10.706 [INFO] Processing done
13:44:10.711 [INFO] Finished in 149.45s
14:15:57.601 [INFO] Output directory set to D:\2024-06-24\Sun-He-rp
14:15:57.601 [INFO] File 2024-06-24-0749_3-Sun-He-rp.ser
14:15:57.601 [INFO] Found Sharpcap metadata. Camera ZWO ASI678MM Binning 1
14:16:29.770 [INFO] Dimensions of raw image determined : 3696x5309
14:16:29.803 [INFO] Processing will require approximatively 673.67MB of disk space
14:16:29.947 [INFO] Detected spectral line Iron (Fe I) with binning 1 (for pixel size 2.00µm)
14:16:29.953 [INFO] Starting reconstruction...
14:16:29.953 [INFO] Distortion polynomial ax3 + bx2 + cx + d = 0
   - a = -7.323243917886016E-11
   - b = 1.3521994335958624E-5
   - c = -0.045643179541491635
   - d = 247.08835704559624
14:17:07.333 [INFO] Reconstruction done. Generating images...
14:17:21.985 [INFO] Black estimate 275.94
14:17:22.507 [INFO] Detected X/Y ratio: 1.16
14:17:57.948 [INFO] Processing done
14:17:57.954 [INFO] Finished in 120.25s
`

**Comment by vnp85** [comment]
My spectral resolution *is* high, I can easily see the rugged inside, the splitting of the Calcium lines, for example -- random frame of the Sol'Ex in Ca H

![image](https://github.com/melix/astro4j/assets/21062213/1384118b-e03d-4320-b325-68cfa3e6cc1b)

and right next to it, hydrogen epsilon

![image](https://github.com/melix/astro4j/assets/21062213/7c914faf-fc2d-49c2-a182-96bc7b3ca5af)

**Comment by vnp85** [comment]
So, is that particular line's presence a must? Marked on the image

![image](https://github.com/melix/astro4j/assets/21062213/bb9507e8-8997-4b5c-9019-2d1eb8558964)

**Comment by melix** [comment]
Yes, as I said, auto-detection of the He D3 line will **only** work if either the Fe I or So D2 lines is visible in the crop window. If it's not, JSol'Ex may confuse other lines with the Fe1/D2 lines. This doesn't prevent you from using a different reference line, but in this case you have to go through scripting.

**Comment by vnp85** [comment]
Thanks for clarifying. 

The problem, perhaps for others as well, will be that the small pixels increase the vertical distance between the line candidates, and the data penalty, being additional area, is a square. I have 5 pixels (of 2 μm) where others have 4 (of 2.4 μm).

**Comment by melix** [comment]
The problem isn't much the distance between the lines, it's having a reference to compare with. However, you may want to use binning to reduce the size of your SER files. Using bin1 works if you have excellent observing conditions.

**Comment by vnp85** [comment]
The computational penalty for having to include a pixel-distant spectral line is the readout speed / framerate in particular, not the video size per se. If there is curvature in the line, it makes things much worse.

Binning may or may not be a solution, as spectrally I fell like I have wonderful resolution.

**Comment by vnp85** [comment]
(I just checked the difference between CaH on band and plus-minus 3. Binning is out of question :D)

**Comment by stefanoaz** [comment]
Hi Cèdric:
I've been out of town a week. Now, when I use V2.5.1, the autodetection for He_d3 with a Sodium_d2 line is broken, it only produces the d2 line result. This autodetection function worked nicely in V2.4.9.  Did a procedure change? Did the code change?

Steve

**Comment by stefanoaz** [comment]
Here's part of the (new) problem. Even though I have a binning of 1 selected in the observation details, and both the Sodium d2 line and the He d3 line are in the frame, the run log shows this:

"Detected spectral line H-alpha with binning 2 (for pixel size 2.00µm)"

There must have been a change in the code which has somehow hard-coded bin 2 when Autodetect is used for the wavelength.

**Comment by vnp85** [comment]
I have also experienced problems with the 2.5.1 release and Sodium, (namely getting stuck with the sodium image processing), I think that issue is a bit different than what I exposed here.

**Comment by stefanoaz** [comment]
In the V2.4.9 version, similar frames produced this proper comment in the log:

11:11:01.420 [INFO] Detected spectral line Sodium (D2) with binning 1 (for pixel size 2.00µm)

I have verified that manual pixel offset does produce a helium image in my new SER files. Nothing has changed on my end since V2.4.9.

**Comment by melix** [comment]
> There must have been a change in the code which has somehow hard-coded bin 2 when Autodetect is used for the wavelength.

There is no such thing. You have to be aware that spectral line detection is a sensitive algorithm, which works reasonably well, but can fail. Therefore, unless _the same file_ worked in 2.4.9 and fails in 2.5.1, this cannot be considered a regression. I personally regularly experience failures in auto-detection, and experienced that even in 2.4.9. However, should the detection fail, you always have the ability to set explicitly the line that serves as reference in the cropping windows (e.g Sodium D2 or Iron Fe I).

The binning detection only triggers if there's no .txt metadata file alongside the SER file. Is this the case?

**Comment by vnp85** [comment]
_The binning detection only triggers if there's no .txt metadata file alongside the SER file. Is this the case?_

Is JSol'Ex able to detect the cameraSettings.txt even when the names are a bit off?
Here's an example from my archive, it happens when I record with the SHG: opening the record window some 30 seconds before the actual recording places the first frame of the ser file.

![image](https://github.com/melix/astro4j/assets/21062213/7a2b2f58-23c7-4a5b-bfaa-4a793055059b)

**Comment by melix** [comment]
> Is JSol'Ex able to detect the cameraSettings.txt even when the names are a bit off?

No, the file names must match.

**Comment by stefanoaz** [comment]
Okay - I can verify that V2.5.1 does properly autodetect a SER file that was previously correctly autodetected by V2.4.9. So my new files from today might be a bit off for a sensitive algorithm - I was fighting with high cirrus clouds in the early part of the morning. The d2 and d3 lines were clearly there, but slight cirrus might have caused an issue.

I do not understand why, if I explicitly declared Bin 1 in the observation details, the program can ignore this in the autodetect when autodetect fails. The camera was set to bin 1. I have metadata in the metadata tab, but I'm not sure of the file you are referring to for metadata - I only see the run log in the window manager. Is there a location for metadata info?

**Comment by melix** [comment]
> I do not understand why, if I explicitly declared Bin 1 in the observation details, the program can ignore this in the autodetect when autodetect fails. The camera was set to bin 1. I have metadata in the metadata tab, but I'm not sure of the file you are referring to for metadata - I only see the run log in the window manager. Is there a location for metadata info?

Right let me clarify. There's the _acquisition software metadata file_, which is the `.txt` file which lives alongside the SER file, and is written typically by SharpCap. If this file is found, then the camera name and binning are read from this file automatically, and assumed _correct_. Therefore it doesn't matter what you set in the observation details, it's this metadata file which tells us what to use.

The metadata tab is something specific to JSol'Ex, and shows the different operations which were executed on an image, the pixel shift, etc...

**Comment by vnp85** [comment]
I doublechecked it, kind of a false alarm. It's when it's WinJupos filenames checked in the sharpcap options, AND also interference from my folder-watching renamer, as Sharpcap intends to rename the settingsTxt when it's done recording. Thus, unrealted (and in fact a bug in my ersatz-obsi software stack). As a side effect, in my case it could be that it is this that hinders the binning detection ineffective, although in the opening dialog of JSol'Ex, I manually set the binning and pixel size to the right values.

**Comment by stefanoaz** [comment]
Hi Cedric:

So - the answer to your acq metadata question in yes - the acq metadata .txt file is *always* present alongside the ser file in the same directory, for both the cases that fail autodetect and those which pass. My capture software is Firecapture. Here is the file text for a failing autodetect which mistakenly indicates bin2:

FireCapture v2.7.14 Settings
------------------------------------
Camera=QHY5III678M
Filter=L
Profile=Sun
Filename=Sun_073954.ser
Date=062724
Date(UT)=062724
Start=073943.076
Mid=073954.757
End=074006.439
Start(UT)=143943.076
Mid(UT)=143954.757
End(UT)=144006.439
Duration=23.363s
Date_format=MMddyy
Time_format=HHmmss
LT=UT -7h
Frames captured=2988
FPS (avg.)=127
File type=SER
Binning=1x1
Data=Mono
ROI=3472x340
ROI(Offset)=200x484
Shutter=4.900ms
Gain=38 (15%)
Offset=0
Brightness=0
Contrast=5
HighSpeed=off
USBTraffic=0
Histogramm(min)=0
Histogramm(max)=5
Histogramm=0%
Noise(avg.deviation)=n/a
Limit=10000 Frames

---------- ROI offset positions ----------
Frame 1:	200x484

**Comment by melix** [comment]
Thanks, but as I said, it's not because you have the metadata file that autodetection will succeed. IF there's a metadata file, then the binning that it contains is deemed accurate, but that's pretty much it.

**Comment by stefanoaz** [comment]
Did you test this with Firecapture? The Firecapture metadata is declaring bin 1 as the string "1x1". Not sure if that's what Shartpcap says for Bin 1.  I thought jSolex was using the metadata. True?

**Comment by melix** [comment]
Yes I tested this with Firecapture. It's fairly easy to tell if the metadata file was found, the logs will contain an entry such as:

> Found Firecapture metadata. Camera ZWO ASI178MM Binning 1

**Comment by stefanoaz** [comment]
Here's a logfile from a successful autodetect session. It does not contain the entry you mention, even though the acq txt file is there, beside the ser file on the same level in the directory.

14:23:35.275 [INFO] Output directory set to /Volumes/T7/Firecapture/Sun/061824
14:23:35.275 [INFO] File Sun_065905copy.ser
14:24:39.048 [INFO] Dimensions of raw image determined : 3500x2973
14:24:39.050 [INFO] Processing will require approximatively 535.87MB of disk space
14:24:39.061 [INFO] Starting reconstruction...
14:24:39.061 [INFO] Distortion polynomial ax3 + bx2 + cx + d = 0
   - a = -6.445844635999701E-12
   - b = 1.3125613798716064E-5
   - c = -0.046854744019144884
   - d = 308.5286352458865
14:25:43.838 [INFO] Reconstruction done. Generating images...
14:25:46.962 [INFO] Black estimate 689.56
14:25:46.994 [INFO] Detected X/Y ratio: 0.73
14:25:47.533 [INFO] Diameter 3106.84
14:25:47.678 [INFO] Dimensions of geometry corrected image determined : 3728x3728
14:25:50.468 [INFO] Diameter 3106.84
14:25:53.880 [INFO] Processing done
14:25:53.880 [INFO] Finished in 138.60s
14:26:36.750 [INFO] Output directory set to /Volumes/T7/Firecapture/Sun/061824
14:26:36.750 [INFO] File Sun_065905copy.ser
14:27:41.696 [INFO] Dimensions of raw image determined : 3500x2973
14:27:41.698 [INFO] Processing will require approximatively 535.87MB of disk space
14:27:41.761 [INFO] Detected spectral line Sodium (D2) with binning 1 (for pixel size 2.00µm)
14:27:41.762 [INFO] Starting reconstruction...
14:27:41.762 [INFO] Distortion polynomial ax3 + bx2 + cx + d = 0
   - a = -6.445844635999701E-12
   - b = 1.3125613798716064E-5
   - c = -0.046854744019144884
   - d = 308.5286352458865
14:28:49.027 [INFO] Reconstruction done. Generating images...
14:28:52.910 [INFO] Black estimate 2754.60
14:28:52.937 [INFO] Detected X/Y ratio: 0.73
14:28:55.129 [INFO] Diameter 3106.85
14:29:10.151 [INFO] Processing done
14:29:10.152 [INFO] Finished in 153.40s
14:45:33.676 [INFO] Output directory set to /Volumes/T7/Firecapture/Sun/061824
14:45:33.677 [INFO] File Sun_065905copy.ser
14:46:36.555 [INFO] Dimensions of raw image determined : 3500x2973
14:46:36.557 [INFO] Processing will require approximatively 535.87MB of disk space
14:46:36.616 [INFO] Detected spectral line Sodium (D2) with binning 1 (for pixel size 2.00µm)
14:46:36.616 [INFO] Starting reconstruction...
14:46:36.616 [INFO] Distortion polynomial ax3 + bx2 + cx + d = 0
   - a = -6.445844635999701E-12
   - b = 1.3125613798716064E-5
   - c = -0.046854744019144884
   - d = 308.5286352458865
14:47:40.036 [INFO] Reconstruction done. Generating images...
14:47:43.837 [INFO] Black estimate 2754.60
14:47:43.871 [INFO] Detected X/Y ratio: 0.73
14:47:46.427 [INFO] Diameter 3106.85
14:48:01.694 [INFO] Processing done
14:48:01.694 [INFO] Finished in 148.01s

**Comment by melix** [comment]
what's the file name of your .txt file? It should be `Sun_065905copy.txt`

**Comment by stefanoaz** [comment]
It is. And in no other of my autodetect or any other sessions, is a mention of the metadata file found in the logfile. Here's the directory structure...

<img width="766" alt="Screenshot 2024-06-27 at 15 14 41" src="https://github.com/melix/astro4j/assets/28873616/329b98ce-3346-4b81-b5a4-5a048563cd40">

**Comment by stefanoaz** [comment]
Text from a different day, different successful autodetect, metadata file present but no mention of it in the log:

10:06:53.991 [INFO] Output directory set to /Volumes/T7/Firecapture/Sun/061724
10:06:53.991 [INFO] File Sun_071422.ser
10:07:54.932 [INFO] Dimensions of raw image determined : 3424x2934
10:07:54.934 [INFO] Processing will require approximatively 517.35MB of disk space
10:07:55.042 [INFO] Detected spectral line Sodium (D2) with binning 1 (for pixel size 2.00µm)
10:07:55.042 [INFO] Starting reconstruction...
10:07:55.042 [INFO] Distortion polynomial ax3 + bx2 + cx + d = 0
   - a = 3.1381065805820366E-11
   - b = 1.2957207069561037E-5
   - c = -0.04866753800639593
   - d = 311.64046507883626
10:08:55.950 [INFO] Reconstruction done. Generating images...
10:08:59.711 [INFO] Black estimate 3170.06
10:08:59.767 [INFO] Detected X/Y ratio: 0.74
10:08:59.902 [INFO] Diameter 3121.17
10:09:02.637 [INFO] Black estimate 3214.33
10:09:02.697 [INFO] Detected X/Y ratio: 0.74
10:09:02.809 [INFO] Diameter 3121.17
10:09:15.127 [INFO] Processing done
10:09:15.199 [INFO] Finished in 141.13s

**Comment by melix** [comment]
I think I have found the bug with parsing Firecapture metadata. Can you try the development version?

**Comment by stefanoaz** [comment]
Cèdric:  I'll try it tonight and report back. Thanks for checking it out.

**Comment by stefanoaz** [comment]
Cédric:

Results were excellent with the parsing fix in V2.5.2. Two things happened.
1. The log file showed: "Found Firecapture metadata. Camera QHY5III678M Binning 1"
2. The SER file that formerly had a malfunction in the autodetect, now properly autodetects and produces clear He_d3 images. It identifies the main line as Sodium D2 instead of H-alpha, and it detected the correct offset of -249.9 pixels.

Here's the log:

Output directory set to /Volumes/T7/Firecapture/Sun/062724
File Sun_073848.ser
Found Firecapture metadata. Camera QHY5III678M Binning 1
Date 2024-06-27T14:38:37.448
SER file contains 2904 frames
Color mode : MONO (2 bytes per pixel, depth = 16 bits)
Width: 3472, height: 340
Solar parameters Carrington rotation = 2285, B0 = 2.51°, L0 = 30.39°, P = -4.02°
Computing average image and detecting limb
Dimensions of raw image determined : 3472x2903
Processing will require approximatively 519.06MB of disk space
Detected spectral line Sodium (D2) with binning 1 (for pixel size 2.00µm)
Starting reconstruction...
Distortion polynomial ax3 + bx2 + cx + d = 0
   - a = 4.708787864009249E-11
   - b = 1.292431256912389E-5
   - c = -0.04880109106271532
   - d = 321.80848712897966
Reconstruction done. Generating images...
Black estimate 565.28
Ellipse rotation angle is 8.111780891986427
Black estimate 349.33
Black estimate 342.66
Black estimate 312.13
Black estimate 349.11
Black estimate 377.51
Black estimate 450.67
Black estimate 335.64
Black estimate 355.85
Tilt angle: -8.00°
Black estimate 341.81
Black estimate 334.10
Black estimate 368.47
Detected X/Y ratio: 0.71
Detected X/Y ratio: 0.71
Detected X/Y ratio: 0.71
Detected X/Y ratio: 0.71
Detected X/Y ratio: 0.71
Detected X/Y ratio: 0.71
Detected X/Y ratio: 0.71
Detected X/Y ratio: 0.71
Detected X/Y ratio: 0.71
Detected X/Y ratio: 0.71
Detected X/Y ratio: 0.71
Detected X/Y ratio: 0.71
Diameter 3113.68
Diameter 3113.68
Diameter 3113.68
Diameter 3113.68
Diameter 3113.68
Diameter 3113.68
Diameter 3113.68
Diameter 3113.68
Dimensions of geometry corrected image determined : 3728x3728
Diameter 3113.68
Diameter 3113.68
Diameter 3113.68
Diameter 3113.68
Dimensions of geometry corrected image determined : 3728x3728
Black estimate 331.67
Detected X/Y ratio: 0.71
Black estimate 303.16
Black estimate 378.46
Detected X/Y ratio: 0.71
Detected X/Y ratio: 0.71
Diameter 3113.68
Diameter 3113.68
Diameter 3113.68
Diameter 3113.68
Image is too dark, skipping gamma stretch
Processing done
Finished in 65.95s

-------

Here's the info in the jSolEx Metadata tab:

Image
  - Title: Helium D3 (continuum)
  - Kind: Processed
  - Path: Sun_073848/processed/20240627_helium_-27_00

Pixel Shift = -249.90 pixels
Transformation history
  - Rotate left
  - Flipping
  - Banding reduction (band size: 23 passes: 7)
  - Geometry correction
  - Autocrop
  - Sharpening

Ellipse parameters C(x,y) = ax² + bxy + cy² + dx + ey + f = 0
   - a = 0.71
   - b = 0.00
   - c = 0.71
   - d = -2636.09
   - e = -2636.09
   - f = 3199831.94
Center = (1864.00,1864.00)

Carrington rotation = 2285, B0 = 2.51°, L0 = 30.39°, P = -4.02°
PixelShiftRange = PixelShiftRange[minPixelShift=-280.0, maxPixelShift=20.0, step=30.0]
Reference coordinates:OFFSET_X[490.32778407505384] OFFSET_Y[-91.00803874030976] MARKER[0.0]

**Comment by stefanoaz** [comment]
With this encouraging result - I will try some Bin2 tomorrow on the Helium and the Ca-H lines, if the clouds cooperate. Observing in Phoenix Arizona in the summer must be done before 0900 local time, or it gets too hot outside.

**Comment by stefanoaz** [comment]
Followup:

As of this morning with V2.5.2dev, Bin2 mode works great on He_d3 and Ca-H, where I do not need the full camera resolution and large file size. jSolEx picks up the metadata info and autopopulates the camera fields in the Observation Details form - I don't remember it doing this before. Significant bug fix - thanks.
