### ISSUE TITLE
positive pixel offset not working in v2.6.0

### ISSUE THREAD

**Issue by smart-underworld** [melix/astro4j#344]
Any positive offsets returned the same image as for 0 offset. Therefore, Doppler images of Ha failed. and the following ImageMath script return a totally black image:

[outputs]
ha_diff = img(0)-img(1)

**Comment by melix** [comment]
Did you get a warning in the logs? This can happen if distorsion correction requires pixels which are outside of your cropping window, typically if the line is not centered.

**Comment by smart-underworld** [comment]
I did see the error in the log for v2.6.0. However, the same ser ran fine
in v2.5.3, with the expected Doppler related images generated.

**Comment by smart-underworld** [comment]
![Screenshot 2024-07-06 151533](https://github.com/melix/astro4j/assets/160078210/6251fab4-5ed3-45b1-bafe-2aeecfa8d07b)

**Comment by melix** [comment]
This is an intentional change, which I actually made following another bug report from you : https://github.com/melix/astro4j/issues/334

Before, this would lead to artifacts. So even if you could generate a Doppler image, it wasn't correct in the sense that some pixels had wrong values.

**Comment by smart-underworld** [comment]
OK. I will expand the capture window. Thanks for this fun project.

**Comment by melix** [comment]
Sure. However I'm puzzled because seeing the image you posted, a pixel shift of 1 should work. There may be a bug in the computation of the limits 🤔

**Comment by smart-underworld** [comment]
I can share my ser file if needed. I do agree that my capture window should suffice for the doppler calculations.

**Comment by smart-underworld** [comment]
FWIW, I considered my older bug report a user error. I should have just used the other side of the spectrum to generate the continuum image to avoid the banding issue. Thus prefer to use the older logic to get back the Doppler images with my existing crop window size.

**Comment by melix** [comment]
Yes, sharing the file would help, thank you!

**Comment by smart-underworld** [comment]
ser file can be found here:

https://drive.google.com/drive/folders/1bPu2zbTwpMz3wPl3JlbdscZ21U1SeoAG?usp=sharing

**Comment by melix** [comment]
Thanks for the file. I understand what's going on here : basically the issue is that the solar limb detection failed, so the whole width is used, and as such, a positive offset is indeed forbidden. I'll check what I can do.

**Comment by vnp85** [comment]
I just confirmed this, in batch processing 2.6.0 didn't produce the positive offsets, from the enumeration. I gave it 1;2;3;4; etc.

**Comment by melix** [comment]
Have you tried the 2.6.1 dev version?

**Comment by vnp85** [comment]
2.6.0 is the latest I tried, with the best results so far from 2.5.0
