### ISSUE TITLE
Bad banding compared to INIT

### ISSUE THREAD

**Issue by smart-underworld** [melix/astro4j#345]
With the same ser file, I get bad banding of the continuum, which may be the source of the bad Doppler result
![Screenshot 2024-07-07 110609](https://github.com/melix/astro4j/assets/160078210/e2d32b90-8521-4fc8-84ba-57928d37659a)
![Screenshot 2024-07-07 110632](https://github.com/melix/astro4j/assets/160078210/a13e0b24-d186-4cc7-9881-503a03516751)

**Comment by melix** [comment]
The cause might be the same as #344 , with incorrect limb detection, which would cause an invalid polynomial.

**Comment by melix** [comment]
It appears that the banding issue is unrelated. It's indeed very present on your image and seems to be interference. What was the setup you used?

**Comment by smart-underworld** [comment]
Since v2.6.0 won't generate the doppler images for you to debug, I used v2.5.3, with these settings:

[config.json](https://github.com/user-attachments/files/16134874/config.json)
![Screenshot 2024-07-08 151157](https://github.com/melix/astro4j/assets/160078210/747ad0b2-c37a-402c-b32d-fe213d7e2618)
![Screenshot 2024-07-08 151212](https://github.com/melix/astro4j/assets/160078210/8b48ecc6-cbd7-4393-a55c-d221785575c6)
![Screenshot 2024-07-08 151230](https://github.com/melix/astro4j/assets/160078210/dbbaa534-90d7-403e-abea-a2fc0c5c32fc)
![Screenshot 2024-07-08 151241](https://github.com/melix/astro4j/assets/160078210/95778f5b-5ded-4fa5-a1f3-6ce744003f57)

**Comment by smart-underworld** [comment]
I actually used a different scope from above. I updated the settings, but got the same result:

![Screenshot 2024-07-08 151729](https://github.com/melix/astro4j/assets/160078210/b0109e23-f574-4312-8c62-bf8de7d82f2c)

**Comment by melix** [comment]
Sorry I wasn't clear enough. It seems that the images you are producing have strong interference fringes. A common cause for this is a polarized ND filter. It is great that INTI can correct this, but as of now JSol'Ex will not. I have tried different ways to fix it, but none is really satisfactory, since while it would fix your image, it will make other images which don't have the problem look "flat", or, worse, introduce more artifacts.

Regarding the doppler images not being generated, you can try the 2.6.1 development version which should already fix this.

**Comment by smart-underworld** [comment]
Strange. I don't use any filters. Just a Herschel solar wedge.

**Comment by melix** [comment]
Could it be that the Herschel wedge has a filter in?

**Comment by smart-underworld** [comment]
I removed the inner ND filter. Just glass reflection now.

**Comment by melix** [comment]
Right. I don't know what could cause this, you'd have to talk to specialists like Christian Buil. I'll see if I can find a way to handle it, but at first glance seems fairly complicated.
