### ISSUE TITLE
Bad result for processed solar disk

### ISSUE THREAD

**Issue by smart-underworld** [melix/astro4j#348]
I tried both 2.5.3 and 2.6.1dev (20240710), my ser file generated OK reconstructed image, but the processed solar disk image looks corrupted. This occurs in 5 out of 20 ser files i scanned today. 

I included the ser file in this shared folder:

https://drive.google.com/drive/folders/1bPu2zbTwpMz3wPl3JlbdscZ21U1SeoAG?usp=sharing

![Screenshot 2024-07-10 132845](https://github.com/melix/astro4j/assets/160078210/bdb733f2-55ae-48dc-bb28-b9e4c6154d59)
![Screenshot 2024-07-10 132905](https://github.com/melix/astro4j/assets/160078210/0ef90de9-8963-40af-be3c-9ec346193c0e)

**Comment by melix** [comment]
I wasn't able to reproduce the problem. Would you mind checking with the latest dev version? You might have to uninstall any previous development version you had before installing the new one.

**Comment by smart-underworld** [comment]
I can confirm the latest dev build (20240711) fixed the issue raised here. I uninstalled the older version before the install of this one.
