### ISSUE TITLE
Flat correction is wrong (polar caps). Feature request: ability to tune or perhaps disable it

### ISSUE THREAD

**Issue by vnp85** [melix/astro4j#364]
Version 2.6.3 dev

Because the polar capping has been observed, I compared the Helium I D3 images generated by JSol'Ex and INTI to exclude an instrument artifact. INTI (on the right) generates no such artifact.

PS: the bad spatial resolution is, in part, a result of the vibrating building. The adjacent building operated a heavy rolling crane.

![image](https://github.com/user-attachments/assets/93007ea4-1d92-4106-9e7d-595b04fb9a82)

Line detection seems fine, and there are no overexposed pixels according to Sharpcap Preview. I have a known reflection issue, a reflection that appears and gets worse when the Sun starts to shine through the slit, and the slit's edge is also visible (but avoided by the disk). 

![image](https://github.com/user-attachments/assets/e599eb58-7e70-467a-95a9-f191eb2e612f)

![image](https://github.com/user-attachments/assets/6330a394-e3e0-4b5a-ac64-cf6048a01854)

**Comment by vnp85** [comment]
The issue seems to appear before the tilt is handled:

![image](https://github.com/user-attachments/assets/670dc182-ac71-46d7-ad79-8f8007ef6f19)

**Comment by vnp85** [comment]
At the edge detection step, the disk still looks decent, no polar caps. The manually defined line here is the 447.15nm + 45pixel, hunting the He I at 447.15nm

![image](https://github.com/user-attachments/assets/dfd36e33-c7b2-4ea7-850b-bfefd7329457)

**Comment by vnp85** [comment]
As I said above, isn't it possible the flat got applied 90 degrees rotated?

**Comment by melix** [comment]
No. I don't want to make processing too complicated. If there's something, it should be automatic. The flat correction assumes that the bands are horizontal. Now, you can try to use scripts to achieve what you want, in addition with the `fix_banding` function which has more options (e.g you can rotate the image, then apply banding correction, then rotate back).

**Comment by vnp85** [comment]
Fair enough.
