### ISSUE TITLE
What is the expected behavoir with Adjust Dispersion checkbox?

### ISSUE THREAD

**Issue by smart-underworld** [melix/astro4j#369]
I am confused with the GUI flow with Spectrum Browser. The checkbox Adjust Dispersion did not behave what you had described in FB. A typical use case is I have an unknown spectrum that I want to identify. It does seem to identify the wavelength range. However, when I try to interact with the buttons like +/- and Adjust dispersion, the auto match no longer works. I would expect a button would exist to re-identify the spectra but clicking on the Adjust Dispersion in either state did not do anything. 

I would also expect to see the wavelength dependent dispersion coefficient displayed somewhere, but failed to find it. 

Attached is a video screenshot of the interaction.

**Comment by smart-underworld** [comment]
https://github.com/user-attachments/assets/cfd5fe65-cb3d-4855-9300-78abe806d9c6

**Comment by vnp85** [comment]
(I'm following)

**Comment by melix** [comment]
Basically, as soon as you zoom in or out (click +/- or use ctrl+mouse wheel), the dispersion is off. Identification will try to match, and for this is always takes dispersion into account, independently of whether the checkbox is selected or not.
