### ISSUE TITLE
download of latest dev package raised antivirus alert and is removed

### ISSUE THREAD

**Issue by smart-underworld** [melix/astro4j#373]
![Screenshot 2024-07-19 082621](https://github.com/user-attachments/assets/d1da7c9e-7f54-4a9c-8da1-d246e83fd8b8)

**Comment by melix** [comment]
Sounds fairly strange, I'd think of a false positive. Rather annoying.

**Comment by melix** [comment]
Seems to be a fairly common false positive :( https://cdromance.org/guides/virus-detected-trojanscript-wacatac-bml/

**Comment by smart-underworld** [comment]
Didn't have this alert with earlier downloads. Wonder if it is related to
the CrowdStrike fiasco today.

**Comment by vnp85** [comment]
No issue here, I downloaded both the "last" 2.6.3 dev, the 2.6.3 and the 2.6.4 dev on multiple machines, albeit probably before microsoft showing us once again its real face.

**Comment by stefanoaz** [comment]
When these positives have been mentioned in the past, I have scanned multiple revs of jSolEx with clamav (on the Mac) and have never found a detection, .

steve

**Comment by smart-underworld** [comment]
Retired downloads and no alerts now. Will close issue
