### ISSUE TITLE
ImageMath Java error when making redshift animations

### ISSUE THREAD

**Issue by stefanoaz** [melix/astro4j#375]
Hi Cèdric:

During the creation of a single redshift animation (out of 5 possible), I get the following error when ImageMath is completing the following an auto_contrast operation:  "Error while processing: java.lang.IllegalArgumentException: auto_contrastfirst argument must be a mono image or a list of images"

At this point the program stalls, but a new SER file can be opened without restarting jSolEx. I get this error with multiple H-alpha SER files. There is no problem with redshift detection and the creation of the image showing the locations. This is with V 2.6.3.

steve

**Comment by melix** [comment]
Is there any more details in the logs that you could share?

**Comment by stefanoaz** [comment]
Hi Cèdric:

Yes - I'll send you a link for both the log and the ser file in a PM.

steve

**Comment by stefanoaz** [comment]
Hi Cèdric:

I couldn't find the PM reply in github so I sent the links to your gmail.

**Comment by melix** [comment]
Thank you sir, found the bug!

**Comment by stefanoaz** [comment]
Merci Beaucoup Cèdric :)
