### ISSUE TITLE
Feature Request: keep the detected Helium line's disk

### ISSUE THREAD

**Issue by vnp85** [melix/astro4j#380]
latest version tested: 2.6.4 dev

_**Current behavior**_: if a sodium or iron line is detected, an automatic helium line extraction occurs, and the helium-continuum difference is saved to the disk. However, the helium line per se is omitted. While it is possible to extract the disk manually, either by adding a pixel offset to the list, or using ImageMath, it is awkward to do this for batch work, especially when one is unsure which line is going to be detected, in relation to the Helium line, or when the line has a fractional position, that half a pixel may matter. Note the filenames in the winfows' titlebar.

![image](https://github.com/user-attachments/assets/200d2114-172b-4b8d-b121-27507b3cf46a)

_**Desired behavior**_: besides the helium-continuum-delta-image, to have the helium disk, similar to the one below, also saved to disk.

![image](https://github.com/user-attachments/assets/7aec698c-213a-402a-980f-6941c746f0c8)

Ultimately, my goal is to assemble pictures that are similar in spirit to the hydrogen images, and having the helium disk saved (as it must be generated somewhere in the background) would be of help:

![image](https://github.com/user-attachments/assets/a56384a3-9805-45f1-a612-a2c152383af1)

**Comment by melix** [comment]
Just as a note: what you "see" if you do this is actually not helium, since it's a very weak emission line. It is similar to looking at a bright lamp where a mosquito passes in front, and you'd say that the image that you see is the image of a mosquito, where the only thing you see is the light of the lamp :)

**Comment by vnp85** [comment]
True, it's a moisquito in front of the lamp. 

I would argue that etalons produce a conceptually similar image. Inspecting up close, one can often times spot the granulation, even when perfectly tuned. The residual light is just too strong in single stack Lunts. See for example László FRANCSICS's image, top right corner https://magyarasztrofotosok.hu/eszleloret/?a=im&i=4080

**Comment by vnp85** [comment]
I mean, H gamma vs H alpha, while both absorption lines, the gamma inverts the active regions, while keeps some of the filaments, quite similar to how the helium line looks.

![image](https://github.com/user-attachments/assets/a748d9cb-105e-44e3-b516-c074705fbc19)

**Comment by melix** [comment]
I'm not too keen on adding too many images, though, as most folks wouldn't care :/

**Comment by vnp85** [comment]
Well, "most folks" post images that show a helium disk with **bright** active regions, for they simply don't understand JSol'Ex's output, never cared to look into the line with their own eyes, and apply a negative to the image named helium, or something, et voila.

The knowledge deficit is real.
