### ISSUE TITLE
ImageMath subtract question, background

### ISSUE THREAD

**Issue by vnp85** [melix/astro4j#387]
version 2.6.5 dev

**Use case**: trying to see "the pure hydrogen epsilon", without the "blue-metal-continuum" that dominates the region (and culminates in the two calcium lines, among others, and gives us the active regions). In JSol'Ex, using custom lines generation and image editing software, and ImageMath. Experimenting in an image editor (expected result) and in ImageMath (surprising result)

**Expecting**: a fairly dark image. As obtained from disk_25 - disk_18, then curved, in image editing software (negative values are clipped to zero).

![image](https://github.com/user-attachments/assets/413bf3b9-c0ca-403c-837b-0c714c619ff6)

**Observing**: an unexpectedly grey image, much like the helium output.

**Questions**: 
- overflow? Autostretch? 
- If A-B would result in a negative value, then positive-offsetting A until no negative number results? 
- Why is the Helium image, which is almost by definition brighter than the synthetic continuum around it, get a bright background?

Thank you.

![image](https://github.com/user-attachments/assets/35c3d21e-63e4-4e1f-9534-61becdb73caa)

**Comment by melix** [comment]
That's correct, JSol'Ex performs normalization so that all values are >= 0 by offsetting.
