### ISSUE TITLE
ImageMath multiplication question

### ISSUE THREAD

**Issue by vnp85** [melix/astro4j#388]
2.6.5 dev

Use case: the hydrogen epsilon line. Trying to get this: 
`mul = ( img(epsilon) - img(continuum) ) * img(epsilon)`

I'm trying to multiply images, and the result is a whiteout. Am I doing something worng? I'd expect a fairly dark, yet meaningful image that awaits stretching.

![image](https://github.com/user-attachments/assets/4357b432-633c-4684-9987-827ca7e637b8)

**Comment by melix** [comment]
So internally pixels are represented with values between 0 and 65536 (NOT [0..1]). Therefore, if you multiply these out, you'd have maximum values which go _beyond_ the max value, hence the white out. You can normalize this by applying a linear stretch after the multiplication. e.g `linear_stretch(( img(epsilon) - img(continuum) ) * img(epsilon))`

**Comment by vnp85** [comment]
It solved it, thanks. 

For some reason (the recurrent issue of what's in one's head is not how things are outside one's head) I thought this would automagically happen, as I saw the image handling is done via doubles, which cannot overflow (with 16 bit images), and just assumed 0~dark .. 1~saturation.

https://github.com/melix/astro4j/blob/main/math/src/main/java/me/champeau/a4j/math/image/ImageMath.java#L420

![image](https://github.com/user-attachments/assets/2e0cc1a3-5be3-43a0-a3e5-be0a70fd56a9)
