### ISSUE TITLE
Problème lors du stacking

### ISSUE THREAD

**Issue by sdevissc** [melix/astro4j#389]
Bien le bonjour, 

J'ai commencé à utiliser JSolex très très récemment, alors tout d'abord merci pour tout ce boulot !!

Je fais face à un petit soucis lors du stacking consécutif à un batch:

J'utilise le script suivant donné dans l'aide:

```
[params]
# banding correction width and iterations
bandingWidth=25
bandingIterations=3
# autocrop factor
cropFactor=1.1
# contrast adjustment
clip=.8

[tmp]
corrected = fix_banding(img(0);bandingWidth;bandingIterations) 
contrast_fixed = clahe(corrected;clip)                         

[outputs]
cropped = autocrop2(contrast_fixed;cropFactor;32)              

# This is where we stack images, simply using a median
# and assuming all images will have the same output size
[[batch]]                                                      
[outputs]
stacked=sharpen(median(cropped))             

```

Dans la log je trouve bien que mes images sont redimensionnées aux même valeurs de longueur et hauteur:

Dimensions of geometry corrected image determined : 4064x4064
Dimensions of geometry corrected image determined : 4064x4064
Dimensions of geometry corrected image determined : 4064x4064
Dimensions of geometry corrected image determined : 4064x4064
Dimensions of geometry corrected image determined : 4064x4064
Dimensions of geometry corrected image determined : 4064x4064
Dimensions of geometry corrected image determined : 4064x4064

Et pourtant je reçois le message suivant:

![image](https://github.com/user-attachments/assets/0d623bc0-d1ba-46d4-a779-72538383d44c)

Est-ce que j'aurais manqué quelque chose?

Merci,

Simon

**Comment by melix** [comment]
Bonjour, 

Le problème vient du fait que les disques solaires n'ont pas forcément la même taille après cropping. La solution est d'essayer avec un multiple plus grand dans l'autocrop, par exemple 64 ou 128.

**Comment by melix** [comment]
Au passage je vous conseille désormais d'utiliser 'auto_contrast' à la place de clahe, avec 1.5 au lieu de .8. il faudrait que je mette à jour la documentation.

**Comment by sdevissc** [comment]
Je viens de tester avec 64 ça fonctionne, merci!

Ok c'est noté pour auto_contrast.
