### ISSUE TITLE
ImageMath error

### ISSUE THREAD

**Issue by vnp85** [melix/astro4j#416]
Version: 2.7.0 dev (from two weeks ago)
RAM: 48GB

While trying to extract the helium, running ImageMath. It's an error I have not encountered before.
JSol'Ex auto extraction works just fine, the error appears only on running a custom script.

![image](https://github.com/user-attachments/assets/010b98a2-74fd-4606-a152-d301a04f62f8)

**Comment by vnp85** [comment]
The HeRaw problem went away when instead of `-142.8` I specified `-143` as the line offset.

**Comment by vnp85** [comment]
Tried to recreate with 2.7.1 dev, didn't happen yet.

```
He_offset = -142.8
He_context = 1
He_step = 1

kontinuum_offset = -135
kontinuum_context = 3
kontinuum_step = 1

kontL = kontinuum_offset - kontinuum_context
kontR = kontinuum_offset + kontinuum_context

HeL = He_offset - He_context
HeR = He_offset + He_context

[outputs]

HeRaw = min(range(HeL,HeR,He_step))
kontinuum = avg(range(kontL,kontR,kontinuum_step))
kontinuumLinearRotated = rotate_rad(linear_stretch(kontinuum), angleP)
delta2 = fix_banding(HeRaw - kontinuum, 100, 50)
HeLog = linear_stretch(log(HeRaw, 2))
HeLogHeRaw = linear_stretch(pow(HeLog + HeRaw, 1.2))
HeMul = linear_stretch(HeLogHeRaw * delta2)
HeMin = min(HeLogHeRaw, HeMul)
HePrime = linear_stretch(HeLog + HeMin + linear_stretch(pow(HeMin,4)) + linear_stretch(pow(HeRaw,2)) + HeLogHeRaw)
HePrimeRot = rotate_rad(HePrime, angleP)
HePrimeRotP = linear_stretch(pow(HePrimeRot, 1.1))
HePrimeRotFinal = linear_stretch(avg(HePrimeRotP, HePrimeRot)) 
```
Wanted to create this
![image](https://github.com/user-attachments/assets/bd51961a-7940-4dad-b57d-7034940ef06e)

**Comment by vnp85** [comment]
Happens with 2.7.1 dev too, which makes it impossible to run the ImageMath script

![image](https://github.com/user-attachments/assets/779f7d03-9477-428f-92ee-d5db0c989da8)

**Comment by melix** [comment]
I guess that's because of autocropping. There are probably (at least) 2 workarounds I can think of:

1. disable autocropping in the process options, and only autocrop the final image you want
2. wrap the `range` call into another autocrop2 call with a custom rounding factor
