### ISSUE TITLE
Doppler Image triggering

### ISSUE THREAD

**Issue by vnp85** [melix/astro4j#417]
Is there a way to force the generation of the doppler image? I have excellent CaK data, all the ticks in the checkbox (custom process, generate doppler, +-3), yet there is no doppler output. Perhaps related to the different nature of the CaK line? I'd use INTI in such situations, as I often do with hydrogen beta,  but it just crashes, as it often does.

**Comment by smart-underworld** [comment]
How did you manage to get good resolution data for CaK? Special optics?

**Comment by vnp85** [comment]
@smart-underworld actually there were some thin clouds, and they may have contributed to calming the air down and provide better than average seeing. Also, my aperture is limited to that of a 2" filter, as I use such filters as ERF to keep the heat out of the scope entirely, while getting the most light possible from within the band. I use Antlia's triband erf in this case. Other than this front ERF hack, it's the standard Sol'Ex with the sagging plastic case, wires and duct tape, on a 62/400 ED scope. I hacked my EQ3, drive the motors myself, and implemented a SHG scanning mode.
 
 Here's a downsampled image of today (haven't published it yet). Compared to what I usually get -- the Ersatz-Obsi is at the office window, a metal roof is in front, a cold stream flows after that and then there are hills, with a cold river after that, ideal observation site, c'est la vie --, this is an excellent frame.
 
 
![image](https://github.com/user-attachments/assets/d85311d0-016d-4dc5-9f0d-34ec9c75af39)

**Comment by smart-underworld** [comment]
That's a beautiful capture of CaK indeed. Congratulations.

**Comment by smart-underworld** [comment]
Good tips on use of the Antlia triband

**Comment by smart-underworld** [comment]
Yes. I am looking at the one for solar (later)

**Comment by melix** [comment]
You can't "force" the generation of Doppler images. It would actually give pretty bad results for Ca in general, hence why it's only enabled for H-alpha. However, generating one with a script is fairly straightforward, e.g :

```

[params]
# Doppler shift (in pixels)
dopplerShift=3.25
# banding correction width and iterations
bandingWidth=25
bandingIterations=3
# autocrop factor
cropFactor=1.2
saturation=1

[tmp]
red=fix_banding(img(dopplerShift);bandingWidth;bandingIterations)
blue=fix_banding(img(-dopplerShift);bandingWidth;bandingIterations)
green=avg(red,blue)
doppler_raw=rgb(red,green,blue)
cropped=autocrop2(doppler_raw;cropFactor)

[outputs]
doppler = saturate(linear_stretch(cropped);saturation)
```

**Comment by vnp85** [comment]
Thank you

**Comment by vnp85** [comment]
The disk doesn't look like much, it also shows a polar cap on the bottom (need to adjust that polynom), but the proms on the right are amazing

![image](https://github.com/user-attachments/assets/9bf4e0a6-0c82-40e5-8bf6-592914d8966f)
