### ISSUE TITLE
Doppler False Coloration not Tilt Corrected

### ISSUE THREAD

**Issue by stefanoaz** [melix/astro4j#430]
Hi Cèdric. This issue is not a regression, it seems to have been present since I started using jSolEx, but became noticeable enough yesterday that I decided to report it. In the two attached dopplergrams, the solar disk and surface details are properly corrected for the angle P (about 26 degrees), but the false coloration seems to show the hemisphere division still with the uncorrected tilt. I don't think there is a setting I have set incorrectly.

Steve

![16_11_18_20241019_doppler](https://github.com/user-attachments/assets/f4b51f14-1fb1-4274-8524-f2e9e9528af1)
![09_43_45_20241020_doppler](https://github.com/user-attachments/assets/b3fd910e-ae97-43b3-baaa-f8c627e2fcfd)

**Comment by stefanoaz** [comment]
I'll have more details this evening (tomorrow morning UTC) - I'll give settings and have a link for an SER file. I always use the tilt autocorrect and it works well. What I noticed was that the disk and features were properly autocorrected, but the coloration in doppler is not. More details tonight.

Thanks Cédric,

Steve

**Comment by stefanoaz** [comment]
Hi Cédric. I have uploaded a ser file to my Dropbox and will send a link to your gmail address.  Attached is a doppler photo corresponding to that ser file. Normally my scans are done in the morning - this was done in the afternoon, and so a meridian flip caused me to use different settings to set up the "Autocorrect P angle" than I normally use. I always use the Autocorrect P angle function.

For this ser file with meridian flip I used: "Flip horizontal axis," and left "Switch red and blue channels" and "Flip vertical axis" unchecked. (In the mornings without meridian flip I have all of these options checked).

The important thing to note is that the solar disk and surface features are properly tilt corrected, but the false coloration has a tilt. I notice this in morning scans too, but the doppler shift coloration is less pronounced, although with roughly the same amount of tilt. 

I am sending the ser file link to your gmail. Scan was made at 21:07 TU on 19 Oct 2024.

steve
![14_07_17_20241019_doppler](https://github.com/user-attachments/assets/db723eb7-3520-4503-9cf3-d5bc1ba95a64)

**Comment by melix** [comment]
So obviously there's something wrong with banding in this test SER file, but it's actually good since we can see what's happening more clearly :) Here's the image I get without P correction:

![14_07_17_0000_14_07_17_doppler](https://github.com/user-attachments/assets/c9b44c11-ac2c-411b-9f7b-01af7f4a18d4)

Now, if I check P angle correction:

![14_07_17_0000_14_07_17_doppler](https://github.com/user-attachments/assets/e0d7252f-540c-45c5-8c1c-16fee8a2250e)

So it looks to me that it behaves correctly? Why would you expect the doppler to be "un-tilted"?

**Comment by melix** [comment]
Sorry about that, I got the orientation wrong. Here's the non-P corrected Doppler:

![14_07_17_0000_14_07_17_doppler](https://github.com/user-attachments/assets/25a68935-0749-4743-9050-24b858e0b544)

and here's the P-corrected one:

![14_07_17_0000_14_07_17_doppler](https://github.com/user-attachments/assets/5e6e8ed9-c374-446a-bd4e-46cd99c464ec)

I'm really sorry but I still don't see your point here.

**Comment by stefanoaz** [comment]
The doppler coloration in large part shows blue on the approaching side of solar rotation, and red on the receding side of rotation. The axis of rotation, when p-corrected, is exactly vertical. So the division between red and blue should also be vertical, and definitely without this strong tilt. And the tilt angle of the bands is roughly the same as when the sun does not have p-angle corrected (although the tilt here is in the opposite sense). 
It behaves as if the coloration is acting on the uncorrected p-angle image, and not on the corrected image.

**Comment by melix** [comment]
Oh, now that you are explaining this... it makes lot of sense as the nose on your face. I don't understand why, this is really curious. Let me think about it.

**Comment by stefanoaz** [comment]
Cédric: I processed the same SER file with INTI and got a similar result with Valerie's code: the disk is aligned but the doppler coloration is tilted. So the phenomenon is in her code too. Not sure yet if anyone has reported it on her end...

Doppler image using INTI (contrast a bit overstretched....)
![_14_07_17_doppler3 0](https://github.com/user-attachments/assets/4847be2e-4a23-4a1f-849e-f736eca37cc5)

**Comment by melix** [comment]
I have made some more tests, using a variety of old scans. I think what you're seeing here is an artifact of "bad" data (e.g here the banding due to reflection probably). Getting a doppler which actually shows the sun rotation is not that trivial. I _think_ it's actually easier to get one by having a scan in DEC instead of RA.

The reason I'm puzzled is because there's nothing really magic in computing the Doppler. The only thing which is done is assigning the blue wing to the blue channel, the red wing to the red channel, and the average of the two to the green one. Therefore, there's no "artificial coloring" going on after some transform: the colors _are_ the data. From the previous scans I've used, I have seen that in most of my Dopplers, the W/E separation is not that obvious, and often shows a "leak" of the blue in the north pole and in the middle to the east direction. The weather conditions are probably influencing, but as I said probably also the scan direction and the speed of scan.

**Comment by stefanoaz** [comment]
Thanks Cédric - that's a pretty thorough explanation, and agrees with my usual results with doppler like the one below. The rotation coloration is more subtle. I believe I still perceive a tilt in the gross coloration associated with rotation (here the "blue chunk" is tilted upward slightly), but perhaps this is an artifact caused by scanning in RA. I could try scanning at 2x RA to see if this changes; normally I scan at 8x (or 20x for stacking frames).

Actually, the fact that I see local coloration around active areas like sunspots, and this is correctly aligned should tell me that there is no mis-alignment between the coloration and the tilt correction.  I'll try the 2x experiment this morning and post the result here just to see if scan rate affects the perceived color "tilt" due to rotation. But I think there is no problem with the code.

![10_51_22_20241028_doppler](https://github.com/user-attachments/assets/6ef76c62-bdc6-48ca-a082-91da8f1c2ea8)

**Comment by melix** [comment]
Christian seems to confirm that the result is expected and likely due to weather conditions. See https://groups.io/g/Solex-project/message/11022

**Comment by stefanoaz** [comment]
Cédric:

I've taken comparison scans at 1x and 8x siderial rate. Let me post the comparison and then I think we can close this. 

I think it would be useful to know if scan rate affects the artifact, just as a clue as to what's going on. I do see a slight tilt in coloration, as mentioned before, even in excellent weather. I think it may be due to using a short focal length doublet, where the focal plane still has a slight sphereicity - it's not perfectly flat. This is a subtle effect.

**Comment by stefanoaz** [comment]
Okay, here's this morning's RA scan at 8x sidereal:
![09_50_03_20241030_doppler](https://github.com/user-attachments/assets/8f6a6185-01de-43e4-b0a6-51ddf04ac101)

And here at 1x sidereal:
![09_58_45_20241030_doppler](https://github.com/user-attachments/assets/ca14c016-4e67-4b6e-ae2f-45059d9f5e49)

So, this leads me to believe this is an effect of seeing and atmospheric turbulence. The 140 second scan had much more banding and coloration. Perhaps the turbulence causes physical motion of the peaks in the spectral line, which distort both the feature data and the doppler data.

This seems to be a real physical effect and the software is fine. Please close this ticket whenever you wish. Thanks Cédric! This was a learning experience.

**Comment by melix** [comment]
Thanks, I learnt something too!
