### ISSUE TITLE
Problem running under Linux Mint/Ubuntu

### ISSUE THREAD

**Issue by mconsidine** [melix/astro4j#45]
Hi,
Can you provide a set of instructions for compiling under Linux?

The .deb files are not working for me on Linux Mint/Ubuntu (install error with GDebi installer):

``
An unhandlable error occured

There seems to be a programming error in aptdaemon, the software that allows you to install/remove software and to perform other package management related tasks.

org.freedesktop.DBus.Error.NoReply: Message recipient disconnected from message bus without replying
``

My system is:
  Kernel: 5.15.0-76-generic x86_64 bits: 64 compiler: gcc v: 11.3.0 Desktop: Cinnamon 5.4.12
    tk: GTK 3.24.33 wm: Mutter dm: GDM3, LightDM Distro: Linux Mint 21 Vanessa
    base: Ubuntu 22.04 jammy

$ java --version
openjdk 11.0.19 2023-04-18
OpenJDK Runtime Environment (build 11.0.19+7-post-Ubuntu-0ubuntu122.04.1)
OpenJDK 64-Bit Server VM (build 11.0.19+7-post-Ubuntu-0ubuntu122.04.1, mixed mode, sharing)

Does this require Java 17?  "./gradlew jsolex:run" fails as well 

Thanks,
Matt

**Comment by melix** [comment]
Hi Matt! I'm actually building under Linux Mint, so it definitely works. You need JDK 17, I recommend you install [GraalVM CE 23 for Java 17](https://www.graalvm.org/).

When you have it on your `JAVA_HOME`, it should simply be a matter of running: `./gradlew :jsolex:run`.

**Comment by mconsidine** [comment]
Hi,
Thanks for that.  Switching to Java 17 allows ./gradlew jsolex:run to work

If I want to compile my own version (I apparently have something going on with GDebi or the .deb file provided, as trying to install it generates an unrecoverable error), how would I do that?  The GraalVM site suggest using a native-image command against bytecode, but theirs is a simple example.

Can you give me some pointers on your workflow to either get an executable I can run in a folder or a .deb that I can install?

Matt

**Comment by melix** [comment]
`native-image` is not the option for packaging JSol'Ex: it would try to generate a native binary but it's missing configuration to work right now.

The easiest is to run `./gradlew jsolex:jpackage` which should generate a `.deb` installer in `jsolex/build/installers`.
Should the installer still fail on your machine, you can still simply package it as:

`./gradlew jsolex:jlink`

which will produce an application under `jsolex/build/image`. You can copy that directory wherever you want and run the application with `bin/jsolex`.

**Comment by mconsidine** [comment]
Thanks again.

I could not get the .deb file created and am wondering if I have some conflict in my path.

That said, "./gradlew jsolex:jlink" did work.

Does the .deb package only install jsolex and jserfile?  Or, put differently, now that I have that working, which of the other programs in the git folder should I compile?  Are there any path settings I should set up?

Thank you!
Matt

**Comment by melix** [comment]
Depends on what you are interested in :) If you only care about JSol'Ex, you're done. If you also want to use the (primitive) SER player, you can do the same `./gradlew ser-player:jlink`.

**Comment by mconsidine** [comment]
Thank you.

Looks like I have a .deb file under jsolex/build/jpackage (vs /installers).  Still have something goofy with GDebi which I need to run down though.  That said, I consider this "solved".

Thanks again!
Matt

**Comment by melix** [comment]
I'm reopening because I need to document this better so that others find out.

**Comment by mconsidine** [comment]
Got it.  FWIW, I solved the issue with using GDebi to install the .deb file by removing the Linux Mint version of gdebi/gdebi-core (apparently there's some issue with aptdaemon) and then installing the Ubuntu version of the same.

I used the Jammy versions found here
  https://pkgs.org/search/?q=gdebi
And used the instructions to install those new .deb files via apt, found here:
  https://linuxhint.com/manual_install_deb_package_cli_ubuntu/

The idea for this approach came from here:
  https://www.reddit.com/r/linux4noobs/comments/11avcde/programming_error_in_aptdaemon_trying_to_install/

Matt
