### ISSUE TITLE
V2.8.0 and 2.8.1_dev do not compute H-gamma line polynomial correctly even when forced

### ISSUE THREAD

**Issue by stefanoaz** [melix/astro4j#464]
Hi Cèdric:

This seems to be a regression, since jSolEx V2.7.3 computes the polynomial properly on the same SER file. In particular, it is odd that even though I can fit the poly to a frame and lock it in the editor, it doesn't seem to make a difference in the final rendering. There are no problems with this in V2.7.3. There are also no problems (yet) on H-alpha, He-d, and CaH with the new versions.

I will send the ser file dropbox link to your gmail.

Steve

**Comment by melix** [comment]
Fixed in b18f05034963321493947514e567d7e6a9e8e222
